name: Update badges

on: push
#   schedule:
#     # Runs at 2am UTC
#     - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: duc-quan-hoang
          CREDLY_SORT: RECENT
