name: Update badges

on:
  schedule:
    - cron: "0 15 1 * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: duc-quan-hoang
          BADGE_SIZE: 110
